create schema if not exists "2026_copa_da_escola";

create table if not exists "2026_copa_da_escola"."resultados_turmas" (
  "id" bigint generated by default as identity primary key,
  "cd_escola" integer,
  "cd_turma" bigint,
  "ds_turma" text,
  "fase" integer not null,
  "rodada" integer not null,
  "pct_frequencia" numeric(8, 3),
  "pontos_frequencia" integer,
  "pct_realizacao" numeric(8, 3),
  "pontos_tarefas" integer,
  "pct_acerto" numeric(10, 6),
  "pontos_acertos" integer,
  "nr_serie" integer,
  "pontos_total" integer,
  "colocacao_escola" integer,
  "nr_classe" integer,
  "nm_escola" text,
  "nm_diretoria" text,
  "cd_diretoria" integer
);

grant usage on schema "2026_copa_da_escola" to anon, authenticated, service_role;
grant all privileges on all tables in schema "2026_copa_da_escola" to service_role;
grant select on all tables in schema "2026_copa_da_escola" to anon, authenticated;
alter default privileges in schema "2026_copa_da_escola" grant all on tables to service_role;
alter default privileges in schema "2026_copa_da_escola" grant select on tables to anon, authenticated;

create index if not exists "idx_resultados_turmas_fase_rodada"
  on "2026_copa_da_escola"."resultados_turmas" ("fase", "rodada");

create index if not exists "idx_resultados_turmas_regional_escola"
  on "2026_copa_da_escola"."resultados_turmas" ("nm_diretoria", "nm_escola");

create index if not exists "idx_resultados_turmas_serie"
  on "2026_copa_da_escola"."resultados_turmas" ("nr_serie");

create or replace function public.get_dashboard_filters(
  p_fase integer,
  p_rodada integer
)
returns table (
  regional text,
  escola text,
  serie integer
)
language sql
stable
security definer
set search_path = public
as $$
  select distinct
    nullif(trim(t.nm_diretoria), '') as regional,
    nullif(trim(t.nm_escola), '') as escola,
    t.nr_serie as serie
  from "2026_copa_da_escola"."resultados_turmas" t
  where t.fase = p_fase
    and t.rodada = p_rodada
  order by 1 nulls last, 2 nulls last, 3 nulls last;
$$;

create or replace function public.get_seduc_table(
  p_fase integer,
  p_rodada integer,
  p_series integer[] default null
)
returns table (
  regional text,
  "totalEscolas" bigint,
  "totalTurmas" bigint,
  pontuacao numeric,
  frequencia numeric,
  tarefas numeric,
  acertos numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(nullif(trim(t.nm_diretoria), ''), 'Nao informado') as regional,
    count(distinct t.cd_escola)::bigint as "totalEscolas",
    count(distinct t.cd_turma)::bigint as "totalTurmas",
    round(avg(t.pontos_total)::numeric, 2) as pontuacao,
    round(avg(t.pontos_frequencia)::numeric, 2) as frequencia,
    round(avg(t.pontos_tarefas)::numeric, 2) as tarefas,
    round(avg(t.pontos_acertos)::numeric, 2) as acertos
  from "2026_copa_da_escola"."resultados_turmas" t
  where t.fase = p_fase
    and t.rodada = p_rodada
    and (p_series is null or t.nr_serie = any (p_series))
  group by 1
  order by pontuacao desc, regional asc;
$$;

create or replace function public.get_ure_table(
  p_fase integer,
  p_rodada integer,
  p_regional text,
  p_series integer[] default null
)
returns table (
  escola text,
  "totalTurmas" bigint,
  pontuacao numeric,
  frequencia numeric,
  tarefas numeric,
  acertos numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(nullif(trim(t.nm_escola), ''), 'Nao informado') as escola,
    count(distinct t.cd_turma)::bigint as "totalTurmas",
    round(avg(t.pontos_total)::numeric, 2) as pontuacao,
    round(avg(t.pontos_frequencia)::numeric, 2) as frequencia,
    round(avg(t.pontos_tarefas)::numeric, 2) as tarefas,
    round(avg(t.pontos_acertos)::numeric, 2) as acertos
  from "2026_copa_da_escola"."resultados_turmas" t
  where t.fase = p_fase
    and t.rodada = p_rodada
    and coalesce(nullif(trim(t.nm_diretoria), ''), 'Nao informado') = p_regional
    and (p_series is null or t.nr_serie = any (p_series))
  group by 1
  order by pontuacao desc, escola asc;
$$;

create or replace function public.get_escola_table(
  p_fase integer,
  p_rodada integer,
  p_regional text,
  p_escola text,
  p_series integer[] default null
)
returns table (
  turma text,
  pontuacao numeric,
  frequencia numeric,
  tarefas numeric,
  acertos numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(nullif(trim(t.ds_turma), ''), 'Nao informado') as turma,
    round(t.pontos_total::numeric, 2) as pontuacao,
    round(t.pontos_frequencia::numeric, 2) as frequencia,
    round(t.pontos_tarefas::numeric, 2) as tarefas,
    round(t.pontos_acertos::numeric, 2) as acertos
  from "2026_copa_da_escola"."resultados_turmas" t
  where t.fase = p_fase
    and t.rodada = p_rodada
    and coalesce(nullif(trim(t.nm_diretoria), ''), 'Nao informado') = p_regional
    and coalesce(nullif(trim(t.nm_escola), ''), 'Nao informado') = p_escola
    and (p_series is null or t.nr_serie = any (p_series))
  order by pontuacao desc, turma asc;
$$;

grant execute on function public.get_dashboard_filters(integer, integer) to anon, authenticated, service_role;
grant execute on function public.get_seduc_table(integer, integer, integer[]) to anon, authenticated, service_role;
grant execute on function public.get_ure_table(integer, integer, text, integer[]) to anon, authenticated, service_role;
grant execute on function public.get_escola_table(integer, integer, text, text, integer[]) to anon, authenticated, service_role;
